---
title: "Experiment A List Design"
author: "Rachel"
date: /today
geometry: margin = 2cm
header-includes:
  - /usepackage{booktabs}
  - /usepackage{siunitx}
  - /usepackage{tabto}
  - /usepackage{soul}
  - /usepackage{xcolor}
  - /usepackage{placeins}
  - /usepackage{lscape}
  - /usepackage{animate}
  - /newcommand{/blandscape}{/begin{landscape}}
  - /newcommand{/elandscape}{/end{landscape}}
  - /makeatletter/renewcommand{/fps@table}{!ht}/makeatother
  - /setstcolor{red}
  - /usepackage{sectsty}
  - /sectionfont{/color{blue}} 
  - /subsectionfont{/color{blue}}
  - /subsubsectionfont{/color{darkgray}}

output:
  pdf_document: 
    fig_caption: yes
    fig_width: 7
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 4
  fontsize: 10pt
editor_options: 
  chunk_output_type: inline
---   
***
# Housekeeping   
The purpose of this file is to create the lists for Experiment 1.  
_Goal:_ To create csv files that contain the .wav filenames to be called for every possible block in Experiment A.  
*Color file here: http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf*  
*crtl + I for reformat*   

## Knitting    
```{r Knitting, include=F}

library(knitr)

opts_chunk$set(
  dev = 'pdf',
  comment = "", 
  echo = FALSE, 
  warning = TRUE, 
  message = TRUE,
  cache = FALSE, 
  size = "small",
  tidy.opts = list(width.cutoff = 200),
  fig.width = 8, 
  fig.height = 4.5, 
  fig.align = "center")

def.chunk.hook  <- knitr::knit_hooks$get("chunk")

knitr::knit_hooks$set(
  chunk = function(x, options) {
    x <- def.chunk.hook(x, options)
    ifelse(
      options$size != "normalsize", 
      paste0(
        "/n //", 
        options$size,
        "/n/n", 
        x, 
        "/n/n //normalsize"), 
      x)
  })

color_block = function(color) {
  function(x, options)        sprintf('//color{%s}//begin{verbatim}%s//end{verbatim}//color{black}', color, x)
}
knitr::knit_hooks$set(error = color_block('red'))
knitr::knit_hooks$set(warning = color_block('orange'))
```

## Libraries   
```{r Library, include=F}
library(tidyverse)
library(magrittr)
library(broom)          # for extraction of coefficients
library(gganimate)      # to animate plots
library(RColorBrewer)   # to select brewer colors
library(kableExtra) 
library(lme4)
library(lmerTest)
library(ggpubr)
library(data.table)
library(jsonlite)
```

```{r, Format, include=F}
options(width = 110)
theme_set(theme_bw())
```
_____
```{r}
sortVars <- function(.data) {
  .data %>%
    relocate(
      ParticipantID,
      ExposureOrder,
      TestOrder,
      starts_with("AttendedTalker"),
      Phase,
      Block,
      Trial,
      starts_with("Item."), 
      Filename,
      Response,
      Response.Correct,
      Attended.Talker_Sound,
      starts_with("Attended.Talker"),
      Unattended.Talker_Sound,
      starts_with("Unattended.Talker"),
      starts_with("resp"),
      starts_with("Response"),
      starts_with("speaker_"),
      Assignment.Comment,
      starts_with("Participant."), 
      starts_with("audio_"),
      starts_with("Duration"),
      starts_with("Time"),
      starts_with("Assignment.Submit"),
      userDateTimeAtSubmit,
      userDateTimeAtInitialization,
      userAgent,
      word_recall,
      participant_id,
      everything())
}
```


```{r}
experiment = "experiment.a"
  read_csv(
    "C:/Users/Rachel/Documents/SI.SP/data/experiment.a/data.csv",
    show_col_types = FALSE) %>%

formatData(experiment = experiment) %>%
sortVars() %>%
  view()
  #write.csv(., "C:/Users/Rachel/Documents/SI.SP/data/experiment.a/data2.csv")
```

```{r}
data <- read_csv("C:/Users/Rachel/Documents/SI.SP/data/experiment.a/data2.csv",
    show_col_types = FALSE)
```

# Check  
## Has any participant completed the experiment more than once?  
```{r}
data %>%
  group_by(ParticipantID, userDateTimeAtInitialization) %>%
  summarise() %>%
  group_by(ParticipantID) %>%
  tally() %>% filter(n != 1)
```

## Are there the right number of Blocks?  
```{r Check number of blocks}
data %>%
  group_by(ParticipantID, Block) %>%
  summarise() %>%   
  tally() %>%
  group_by(ParticipantID) %>%
 filter(n != 23)
```

```{r Check number of trials per block}
data %>%
  group_by(ParticipantID, Phase, Block, Trial) %>%
  summarise() %>%   
  tally() %>%
  group_by(ParticipantID) %>%
 filter(n != 1) %>%
 filter(n != 6) %>%
 filter(n != 8)
```

```{r Correct # of Filler and Critical trials per exposure block}
data %>%
  group_by(ParticipantID, Phase, Block, Item.Type, Trial) %>%
  summarise() %>%   
  tally() %>%
  filter(Phase == "Exposure") %>%
  filter(Item.Type == "Critical" & n != 2 | 
         Item.Type == "Filler" & n != 6)
```

```{r Correct # Test trials per test block}
data %>%
  group_by(ParticipantID, Phase, Block, Trial) %>%
  summarise() %>%   
  tally() %>%
  filter(Phase == "Test") %>%
  filter(n != 6)
```


 

### Test  
```{r Check number of critical trials per exposure block}
data %>%
  group_by(ParticipantID, Block) %>%
  summarise() %>%
  group_by(Item.Type) %>%
  tally() %>% filter(n != 1)
```


