---
title: "Experiment 1 List Design"
author: "Rachel"
date: /today
geometry: margin = 2cm
header-includes:
  - /usepackage{booktabs}
  - /usepackage{siunitx}
  - /usepackage{tabto}
  - /usepackage{soul}
  - /usepackage{xcolor}
  - /usepackage{placeins}
  - /usepackage{lscape}
  - /usepackage{animate}
  - /newcommand{/blandscape}{/begin{landscape}}
  - /newcommand{/elandscape}{/end{landscape}}
  - /makeatletter/renewcommand{/fps@table}{!ht}/makeatother
  - /setstcolor{red}
  - /usepackage{sectsty}
  - /sectionfont{/color{blue}} 
  - /subsectionfont{/color{blue}}
  - /subsubsectionfont{/color{darkgray}}

output:
  pdf_document: 
    fig_caption: yes
    fig_width: 7
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 4
  fontsize: 10pt
editor_options: 
  chunk_output_type: inline
---   
***
# Housekeeping   
The purpose of this file is to create the lists for Experiment 1.
*Color file here: http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf*
*crtl + I for reformat*  

## Knitting    
```{r Knitting, include=F}

library(knitr)

opts_chunk$set(
  dev = 'pdf',
  comment = "", 
  echo = FALSE, 
  warning = TRUE, 
  message = TRUE,
  cache = FALSE, 
  size = "small",
  tidy.opts = list(width.cutoff = 200),
  fig.width = 8, 
  fig.height = 4.5, 
  fig.align = "center")

def.chunk.hook  <- knitr::knit_hooks$get("chunk")

knitr::knit_hooks$set(
  chunk = function(x, options) {
    x <- def.chunk.hook(x, options)
    ifelse(
      options$size != "normalsize", 
      paste0(
        "/n //", 
        options$size,
        "/n/n", 
        x, 
        "/n/n //normalsize"), 
      x)
  })

color_block = function(color) {
  function(x, options)        sprintf('//color{%s}//begin{verbatim}%s//end{verbatim}//color{black}', color, x)
}
knitr::knit_hooks$set(error = color_block('red'))
knitr::knit_hooks$set(warning = color_block('orange'))
```

## Libraries   
```{r Library, include=F}
library(tidyverse)
library(magrittr)
library(broom)          # for extraction of coefficients
library(gganimate)      # to animate plots
library(RColorBrewer)   # to select brewer colors
library(kableExtra) 
library(lme4)
library(lmerTest)
library(ggpubr)
library(data.table)
```

```{r, include=F}
options(width = 110)
theme_set(theme_bw())
```

_____

# Lists  
## Exposure Phase    
### Critical Items     
```{r Ciritcal Items}
# Table with the information on how the stims should be paired: Materials x Accent x Gender x Ear Assignment

## Word list -> removes reliance on order

### Materials A
Materials.A_S.Words = c(  
  "Parasite",
  "Obscene",
  "Medicine",
  "Tennessee",
  "Peninsula",
  "Hallucinate",
  "Arkansas",
  "Compensate",
  "Dinosaur",
  "Rehearsal"
)

Materials.A_Sh.Words = c(
  "Ambition",
  "Machinery",
  "Brochure",
  "Official",
  "Crucial",
  "Pediatrician",
  "Flourishing",
  "Reassure",
  "Graduation",
  "Vacation"
)

## Materials B
Materials.B_S.Words = c(
  "Pregnancy",
  "Democracy",
  "Embassy",
  "Legacy",
  "Reconcile",
  "Personal",
  "Eraser",
  "Episode",
  "Literacy",
  "Coliseum"
)

Materials.B_Sh.Words= c(
  "Initial",
  "Beneficial",
  "Negotiate",
  "Commercial",
  "Parachute",
  "Efficient",
  "Publisher",
  "Glacier",
  "Refreshing",
  "Impatient"  
)

## Items
tibble(
  
  Phase = c(
    rep("Exposure", 20)
  ),
  
  Item.Type = c(
    rep("Critical", 20)
  ),
  
  Block = c(
    rep("1", 20)
  ),
  
  Item.Number = 1:20,
  
  Talker.A = c(
    Materials.A_Sh.Words, 
    Materials.B_S.Words
  ),
  
  Talker.A_Materials = c(
    rep("Materials A", 10),
    rep("Materials B", 10)
  ),
  
  Talker.A_Sound = c(
    rep("Sh", 10),
    rep("S", 10)
  ),
  
  Talker.B = c(
    Materials.A_S.Words, 
    Materials.B_Sh.Words
  ),
  
  Talker.B_Materials = c(
    rep("Materials A", 10),
    rep("Materials B", 10)
  ),
  
  Talker.B_Sound = c(
    rep("S", 10),
    rep("Sh", 10)
  )
) %>% 
  
  ## Possible Assignments (Shift x Gender x Ear)
  ### Which Talker is Attended to is dependent on instructions
  crossing(
    Attend.To = c(
      "Talker A",
      "Talker B"
    ),
    Version = c(
      "Shifted",
      "Unshifted"
    ),    
    Talker.A_Gender = c(
      "Female", 
      "Male"
    ),
    Talker.A_Ear = c(
      "Left", 
      "Right"
    )
  ) %>%
  
  ## Adds in column noting Gender + Ear Assignment for Talker B
  mutate(
    Talker.B_Gender =
      case_when( 
        Talker.A_Gender == "Female"
        ~ "Male", 
        T ~ "Female"
      )
    ) %>%
  
  mutate(
    Talker.B_Ear =
      case_when(
        Talker.A_Ear == "Left"
        ~ "Right",
        T ~ "Left"
      )
    ) %>%
  
# In context of Attended Talker
  ## Talker
  mutate(
    Attended.Talker = 
      case_when(
      Attend.To == "Talker A"
      ~ Talker.A,
      T ~ Talker.B
      )
  ) %>%
  
  ## Talker Materials 
   mutate(
    Attended.Talker_Materials = 
      case_when(
      Attend.To == "Talker A"
      ~ Talker.A_Materials,
      T ~ Talker.B_Materials
      )
  ) %>%
  ## Sound
  mutate(
    Attended.Talker_Sound = 
      case_when(
      Attend.To == "Talker A"
      ~ Talker.A_Sound,
      T ~ Talker.B_Sound
      )
  ) %>%
  
  ## Gender
  mutate(
    Attended.Talker_Gender = 
      case_when(
      Attend.To == "Talker A"
      ~ Talker.A_Gender,
      T ~ Talker.B_Gender
      )
  ) %>%
  
  ## Ear
  mutate(
    Attended.Talker_Ear = 
      case_when(
      Attend.To == "Talker A"
      ~ Talker.A_Ear,
      T ~ Talker.B_Ear
      )
  ) %>%
  
  # In context of Unattended Talker
  ## Talker
  mutate(
    Unattended.Talker = 
      case_when(
      Attend.To == "Talker B"
      ~ Talker.A,
      T ~ Talker.B
      )
  ) %>%
  
  ## Talker Materials 
   mutate(
    Unattended.Talker_Materials = 
      case_when(
      Attend.To == "Talker B"
      ~ Talker.A_Materials,
      T ~ Talker.B_Materials
      )
  ) %>%
  ## Sound
  mutate(
    Unattended.Talker_Sound = 
      case_when(
      Attend.To == "Talker B"
      ~ Talker.A_Sound,
      T ~ Talker.B_Sound
      )
  ) %>%
  
  ## Gender
  mutate(
    Unattended.Talker_Gender = 
      case_when(
      Attend.To == "Talker B"
      ~ Talker.A_Gender,
      T ~ Talker.B_Gender
      )
  ) %>%
  
  ## Ear
  mutate(
    Unattended.Talker_Ear = 
      case_when(
      Attend.To == "Talker B"
      ~ Talker.A_Ear,
      T ~ Talker.B_Ear
      )
  ) %>%
  
# Talker 1 
  mutate(
    Talker = 
      case_when(
        Talker.A_Ear == "Left"
        ~ "1",
        T ~ "2"
      )
  ) %>%
  
  ## List
  mutate(
    List = 
      case_when(
        
        ### 01
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials A" &
          Version == "Unshifted" &
          Talker.A_Gender == "Female" &
          Talker.A_Ear == "Left"
        ~ "01",
        
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials B" &
          Version == "Shifted" &
          Talker.A_Gender == "Female"  &
          Talker.A_Ear == "Left"
        ~ "01",
        
        ### 02
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials B" &
          Version == "Unshifted" &
          Talker.A_Gender == "Female" &
          Talker.A_Ear == "Left"
        ~ "02",
        
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials A" &
          Version == "Shifted" &
          Talker.A_Gender == "Female"  &
          Talker.A_Ear == "Left"
        ~ "02",
        
        ### 03 
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials A" &
          Version == "Unshifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Right"
        ~ "03",
        
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials B" &
          Version == "Shifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Right"
        ~ "03",
        
        ### 04  
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials B" &
          Version == "Unshifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Right"
        ~ "04",
        
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials A" &
          Version == "Shifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Right"
        ~ "04",  
        
        ### 05 
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials A" &
          Version == "Unshifted" &
          Talker.A_Gender == "Female" &
          Talker.A_Ear == "Right"
        ~ "05",
        
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials B" &
          Version == "Shifted" &
          Talker.A_Gender == "Female" &
          Talker.A_Ear == "Right"
        ~ "05",
        
        ### 06 
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials B" &
          Version == "Unshifted" &
          Talker.A_Gender == "Female" &
          Talker.A_Ear == "Right"
        ~ "06",
        
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials A" &
          Version == "Shifted" &
          Talker.A_Gender == "Female"  &
          Talker.A_Ear == "Right"
        ~ "06",
        
        ### 07 
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials A" &
          Version == "Unshifted" &
          Talker.A_Gender == "Male" &
          Talker.A_Ear == "Left"
        ~ "07",
        
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials B" &
          Version == "Shifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Left"
        ~ "07",
        
        ### 08
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials B" &
          Version == "Unshifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Left"
        ~ "08",
        
        Attend.To == "Talker A" &
          Talker.A_Materials == "Materials A" &
          Version == "Shifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Left"
        ~ "08",
        
        ### 09
        Attend.To == "Talker B" &
          Talker.B_Materials == "Materials A" &
          Version == "Unshifted" &
          Talker.B_Gender == "Male" &
          Talker.B_Ear == "Right"
        ~ "09",
        
        Attend.To == "Talker B" &
          Talker.B_Materials == "Materials B" &
          Version == "Shifted" &
          Talker.B_Gender == "Male"  &
          Talker.B_Ear == "Right"
        ~ "09",
        
        ### 10
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials B" &
          Version == "Unshifted" &
          Talker.A_Gender == "Female" &
          Talker.A_Ear == "Left"
        ~ "10",
        
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials A" &
          Version == "Shifted" &
          Talker.A_Gender == "Female"  &
          Talker.A_Ear == "Left"
        ~ "10",
        
        ### 11
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials A" &
          Version == "Unshifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Right"
        ~ "11",
        
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials B" &
          Version == "Shifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Right"
        ~ "11",
        
        ### 12  
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials B" &
          Version == "Unshifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Right"
        ~ "12",
        
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials A" &
          Version == "Shifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Right"
        ~ "12",  
        
        ### 13 
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials A" &
          Version == "Unshifted" &
          Talker.A_Gender == "Female" &
          Talker.A_Ear == "Right"
        ~ "13",
        
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials B" &
          Version == "Shifted" &
          Talker.A_Gender == "Female" &
          Talker.A_Ear == "Right"
        ~ "13",
        
        ### 14 
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials B" &
          Version == "Unshifted" &
          Talker.A_Gender == "Female" &
          Talker.A_Ear == "Right"
        ~ "14",
        
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials A" &
          Version == "Shifted" &
          Talker.A_Gender == "Female"  &
          Talker.A_Ear == "Right"
        ~ "14",
        
        ### 15 
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials A" &
          Version == "Unshifted" &
          Talker.A_Gender == "Male" &
          Talker.A_Ear == "Left"
        ~ "15",
        
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials B" &
          Version == "Shifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Left"
        ~ "15",
        
        ### 16
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials B" &
          Version == "Unshifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Left"
        ~ "16",
        
        Attend.To == "Talker B" &
          Talker.A_Materials == "Materials A" &
          Version == "Shifted" &
          Talker.A_Gender == "Male"  &
          Talker.A_Ear == "Left"
        ~ "16",
        
      )
  ) %>%
  
  ## Talker A 
  mutate(
    A = 
      paste0(
        
        ### Shift
        case_when(
          Version == "Shifted" 
          ~ paste0("As"),
          Version == "Unshifted" 
          ~ paste0("S")
        ),
        
        ### Sound
        case_when(
          Talker.A_Sound == "S"
          ~ paste0("", sep = "."),
          Talker.A_Sound == "Sh"
          ~ paste0("h", sep = ".")
        ),
        
        ### Talker A Word 
        paste0(Talker.A),
        
        ### Gender Assignment
        case_when(
          Talker.A_Gender == "Female" 
          ~ paste0(sep = ".", "F"), 
          T ~ paste0(sep = ".", "M")
        ),
        
        ### Ear Assignment
        case_when(
          Talker.A_Ear == "Left" 
          ~ paste0(sep = ".", "L"), 
          T ~ paste0(sep = ".", "R")
        )
      )
    ) %>%
  
  view() %>%
  
  ## Talker B
  mutate(
    B = 
      paste0(
        
        ### Shift
        case_when(
          Version == "Shifted" 
          ~ paste0("As"),
          Version == "Unshifted" 
          ~ paste0("S")
        ),
        
        ### Sound
        case_when(
          Talker.B_Sound == "S"
          ~ paste0("", sep = "."),
          Talker.B_Sound == "Sh"
          ~ paste0("h", sep = ".")
        ),
        
        ### Talker B Word
        paste0(Talker.B),
        
        ### Gender Assignment
        case_when(
          Talker.B_Gender == "Female" 
          ~ paste0(sep = ".", "F"), 
          T ~ paste0(sep = ".", "M")
        ),
        
        ### Ear Assignment
        case_when(
          Talker.A_Ear == "Left" 
          ~ paste0(sep = ".", "R"), 
          T ~ paste0(sep = ".", "L")
        )
      )
    ) %>%
  
  view() %>%
  
  # repetition of File within List
  mutate(
    reps = 1
  ) %>%
  
  # feedback
  mutate(
    feedback = FALSE
  ) %>%

  # Changing file names
  mutate(
    filename = 
      paste0(
        "Critical", 
        sep = "_",
        
        ## Order
        case_when(
          Talker == "1"
          ~ paste0(A, sep = "_", B),
          T ~ paste0(B, sep = "_", A)
        ),
        
        ## file suffix  
        paste0(".wav")   
      )
    ) %>%
  
## Remove Columns
  select(
      -c(
      Talker.A, 
      Talker.A_Materials, 
      Talker.A_Sound, 
      Talker.A_Gender, 
      Talker.A_Ear, 
      
      Talker.B, 
      Talker.B_Materials, 
      Talker.B_Sound, 
      Talker.B_Gender, 
      Talker.B_Ear,
      
      Attend.To
      )
  ) %>%
  
  view() %>%

  # CSV Files
  
  ## Remove all columns but file names
  select(-c(A, B, Talker))  %>%
  
  ## Group files
  group_by(List) %>%
  
  group_map(.f = ~ write_csv(.x, file = paste0("C:Stimuli/Experiment_1/Lists/Critical.",  .y$List, ".csv")))
```


### Filler Items   
```{r Filler Items}

# Word List
Set.A_Word = c(
  "America",
  "Blueberry",
  "Camera",
  "Directory",
  "Dynamite",
  "Gardenia",
  "Hamburger",
  "Hurdle",
  "Inhabit",
  "Keyboard",
  "Lengthen",
  "Lingering",
  "Melancholy",
  "Napkin",
  "Ornament",
  "Pineapple",
  "Purgatory",
  "Therapeutic",
  "Tutorial",
  "Wealthy"
)

Set.B_Word = c(
  "Bakery",
  "Bullying",
  "Continually",
  "Document",
  "Eighty",
  "Grammatical",
  "Identical",
  "Interior",
  "Knowingly",
  "Lethal",
  "Lobbying",
  "Membrane",
  "Negate",
  "Outnumber",
  "Parakeet",
  "Platonic",
  "Tactical",
  "Titanium",
  "Umbrella",
  "Worldly"
)

Set.C_Word = c(
  "Ballerina",
  "Burglary",
  "Domineering",
  "Embody",
  "Gullible",
  "Honeymoon",
  "Illuminate",
  "Ironic",
  "Laminate",
  "Liability",
  "Marina",
  "Metrical",
  "Nightmare",
  "Panicking",
  "Pilgrim",
  "Predict",
  "Terminal",
  "Turbulent",
  "Undermine",
  "Wrinkle"
)

Set.A_NonWord = c(
  "Wominid",
  "Ungelnin",
  "Tilegkalo",
  "Rimkeluwar",
  "Rakil",
  "Perkum",
  "Nomerae",
  "Namuary",
  "Logelai", 
  "Lenediaw", 
  "Kelabidel",
  "Inpaki",
  "Hintarber",
  "Gardimuallay",
  "Gairelom",
  "Bikanian",
  "Baliber",
  "Amalar",
  "Ailounam",
  "Acomining"
)

Set.B_Nonword = c(
  "Wojalto",
  "Tounamplem",
  "Ryligal",
  "Rawamtee",
  "Ploupelai",
  "Omperoge",
  "Nempring",
  "Mibgem", 
  "Meidnow",
  "Kermimer",
  "Itempider",
  "Aknid",
  "Ibirak",
  "Halken",
  "Ganla",
  "Dadigal",
  "Bamtell",
  "Anemer",
  "Lilgrai",
  "Admunker"
)

Set.C_Nonword = c(
  "Youmgel",
  "Tymolape",
  "Tamical",
  "Rengime",
  "Pourilar",
  "Almikquary",
  "Niritaly",
  "Makid",
  "Kaldemia",
  "Imdalier",
  "Kloumidiger",
  "Halomimoc",
  "Gerbualo",
  "Galliwinou",
  "Emhoutic",
  "Dilkuaund",
  "Bowidai",
  "Anolipa",
  "Alnadiro",
  "Aigi"
)

# Table
tibble(
  
  Phase = c(
    rep("Exposure", 60) 
  ),
  
  Item.Type = c(
    rep("Filler", 60)
  ),
  
  Block = c(
    rep("1", 60)
  ),  
  
  Item.Number = c(
    rep(1:20,3) 
  ),
  
  Talker.A = c(
    Set.A_Word,
    Set.B_Word,
    Set.C_Word
  ),
  
  Talker.A_Materials = c(
    rep("Set A", 20),
    rep("Set B", 20),
    rep("Set C", 20)
  ),  
  
  Talker.A_Sound = c(
    rep("Word", 60)
  ),
  
  Talker.B = c(
    Set.A_NonWord,
    Set.B_Nonword,
    Set.C_Nonword
  ),
  
  Talker.B_Materials = c(
    rep("Set A", 20),
    rep("Set B", 20),
    rep("Set C", 20)
  ),
  
  Talker.B_Sound = c(
    rep("Nonword", 60)
  )
) %>%
  
  crossing(
    Attend.To = c(
      "Talker A",
      "Talker B"
    ),
    Talker.A_Gender = c(
      "Female", 
      "Male"
    ),
    Talker.A_Ear = c(
      "Left", 
      "Right"
    )
  ) %>%
  
  ## Adds in column noting Gender + Ear Assignment for Talker B
  mutate(
    Talker.B_Gender =
      case_when( 
        Talker.A_Gender == "Female"
        ~ "Male", 
        T ~ "Female"
      )
  ) %>%
  
  mutate(
    Talker.B_Ear =
      case_when(
        Talker.A_Ear == "Left"
        ~ "Right",
        T ~ "Left"
      )
  ) %>%
  
  ## Adds Version
  mutate(
    Version =
      case_when( 
        Talker.A_Gender == "Male" &
          Talker.A_Ear == "Left" 
        ~ "01",        
        
        Talker.A_Gender == "Female" &
          Talker.A_Ear == "Left"
        ~ "02", 
        
        Talker.A_Gender == "Female" &
          Talker.A_Ear == "Right" 
        ~ "03",
        
        Talker.A_Gender == "Male" &
          Talker.A_Ear == "Right"
        ~ "04", 
      )
  ) %>%
  
  ## Adds Combo
  mutate(
    Set.Combo =
      case_when( 
        
        ## Set A    
        Talker.A_Materials == "Set A" &
          Version == "03"
        ~ "1", 
        
        Talker.A_Materials == "Set A" &
          Version == "01"
        ~ "2",
        
        Talker.A_Materials == "Set A" &
          Version == "02"
        ~ "3",
        
        Talker.A_Materials == "Set A" &
          Version == "04"
        ~ "4",
        
        ## Set B    
        Talker.A_Materials == "Set B" &
          Version == "04"
        ~ "1", 
        
        Talker.A_Materials == "Set B" &
          Version == "02"
        ~ "2",
        
        Talker.A_Materials == "Set B" &
          Version == "01"
        ~ "3",
        
        Talker.A_Materials == "Set B" &
          Version == "03"
        ~ "4",
        
        ## Set C    
        Talker.A_Materials == "Set C" &
          Version == "01"
        ~ "1", 
        
        Talker.A_Materials == "Set C" &
          Version == "03"
        ~ "2",
        
        Talker.A_Materials == "Set C" &
          Version == "04"
        ~ "3",
        
        Talker.A_Materials == "Set C" &
          Version == "02"
        ~ "4"
      )
  ) %>%
  
  ## Critical Pairing
  mutate(
    Critical.Pair = 
      case_when(
        Set.Combo == "1" |
          Set.Combo == "4"
        ~ "X",
        T ~ "Y"
      )
  ) %>%
  
  ## Filter
  
  ### Attended Gender
  mutate( 
    A.Gender = 
      case_when(
        Set.Combo == "1" |
          Set.Combo == "3"
        ~ "Female",
        T ~ "Male"
      )
  ) %>%
  
  ### Attended Ear
  mutate( 
    A.Ear = 
      case_when(
        Set.Combo == "2" |
        Set.Combo == "3"
        ~ "Right",
        
        T ~ "Left"
      )
  ) %>%
  
  ## Talker A 
  mutate(
    A = 
      paste0(
        
        ### Talker A Sound
        paste0("W."),
        
        ### Talker A Word 
        paste0(Talker.A),
        
        ### Gender Assignment
        case_when(
          Talker.A_Gender == "Female" 
          ~ paste0(sep = ".", "F"), 
          T ~ paste0(sep = ".", "M")
        ),
        
        ### Ear Assignment
        case_when(
          Talker.A_Ear == "Left" 
          ~ paste0(sep = ".", "L"), 
          T ~ paste0(sep = ".", "R")
        )
        
      )
  ) %>%
  
  ## Talker B
  mutate(
    B = 
      paste0(
        
        ### Talker B Sound
        paste0("N."),
        
        ### Talker B Word
        paste0(Talker.B),
        
        ### Gender Assignment
        case_when(
          Talker.B_Gender == "Female" 
          ~ paste0(sep = ".", "F"), 
          T ~ paste0(sep = ".", "M")
        ),
        
        ### Ear Assignment
        case_when(
          Talker.B_Ear == "Right" 
          ~ paste0(sep = ".", "R"), 
          T ~ paste0(sep = ".", "L")
        )
      )
  ) %>%
  
  # In context of Attended Talker
  ## Talker
  mutate(
    Attended.Talker = 
      case_when(
      Attend.To == "Talker A"
      ~ Talker.A,
      T ~ Talker.B
      )
  ) %>%
  
  ## Talker Materials 
   mutate(
    Attended.Talker_Materials = 
      case_when(
      Attend.To == "Talker A"
      ~ Talker.A_Materials,
      T ~ Talker.B_Materials
      )
  ) %>%
  ## Sound
  mutate(
    Attended.Talker_Sound = 
      case_when(
      Attend.To == "Talker A"
      ~ Talker.A_Sound,
      T ~ Talker.B_Sound
      )
  ) %>%
  
  ## Gender
  mutate(
    Attended.Talker_Gender = 
      case_when(
      Attend.To == "Talker A"
      ~ Talker.A_Gender,
      T ~ Talker.B_Gender
      )
  ) %>%
  
  ## Ear
  mutate(
    Attended.Talker_Ear = 
      case_when(
      Attend.To == "Talker A"
      ~ Talker.A_Ear,
      T ~ Talker.B_Ear
      )
  ) %>%
  
  # In context of Unattended Talker
  ## Talker
  mutate(
    Unattended.Talker = 
      case_when(
      Attend.To == "Talker B"
      ~ Talker.A,
      T ~ Talker.B
      )
  ) %>%
  
  ## Talker Materials 
   mutate(
    Unattended.Talker_Materials = 
      case_when(
      Attend.To == "Talker B"
      ~ Talker.A_Materials,
      T ~ Talker.B_Materials
      )
  ) %>%
  ## Sound
  mutate(
    Unattended.Talker_Sound = 
      case_when(
      Attend.To == "Talker B"
      ~ Talker.A_Sound,
      T ~ Talker.B_Sound
      )
  ) %>%
  
  ## Gender
  mutate(
    Unattended.Talker_Gender = 
      case_when(
      Attend.To == "Talker B"
      ~ Talker.A_Gender,
      T ~ Talker.B_Gender
      )
  ) %>%
  
  ## Ear
  mutate(
    Unattended.Talker_Ear = 
      case_when(
      Attend.To == "Talker B"
      ~ Talker.A_Ear,
      T ~ Talker.B_Ear
      )
  ) %>%
  
  ## Filter column (again)
  mutate(
    Type = 
      case_when(
        Attended.Talker_Gender == "Female"
        ~ "Female",
        T ~ "Male"
      )
  ) %>%
  
  ## Talker 1 
  mutate(
    Talker = 
      case_when(
        Talker.A_Ear == "Left"
        ~ "1",
        T ~ "2"
      )
  ) %>%
  
  ## repetition of File within List
  mutate(
    reps = 1
  ) %>%
  
  # feedback
  mutate(
    feedback = FALSE
  ) %>%
  
  # Remove files
  mutate(
    Remove = 
    case_when(
      Attended.Talker_Materials == "Set A" &
      Attended.Talker_Sound == "Nonword"
      ~ "TRUE",
      
      Attended.Talker_Materials == "Set B" &
      Attended.Talker_Sound == "Word"
      ~ "TRUE",
      
      Attended.Talker_Materials == "Set C" &
      Attended.Talker_Sound == "Word"
      ~ "TRUE",
      
      T ~ "FALSE"
    )
  ) %>%
  
  # Changing file names
  mutate(
    filename = 
      paste0(
        "Critical", 
        sep = "_",
        
        ## Order
        case_when(
          Talker == "1"
          ~ paste0(A, sep = "_", B),
          T ~ paste0(B, sep = "_", A)
        ),
        
        ## file suffix  
        paste0(".wav")   
      )
    ) %>% 
  
  ## Remove Columns
  select(
      -c(
      Talker.A, 
      Talker.A_Materials, 
      Talker.A_Sound, 
      Talker.A_Gender, 
      Talker.A_Ear, 
      
      Talker.B, 
      Talker.B_Materials, 
      Talker.B_Sound, 
      Talker.B_Gender, 
      Talker.B_Ear,
      
      Attend.To
      )
  ) %>%
  
filter(
  Remove == "FALSE"
  ) %>%
  
  view() %>%
  
  # CSV Files
  
  ## Remove columns in CSV File -> only need file names
  select(-c(A, B, Talker, Remove)) %>%
  
  ## Group         
  group_by(Set.Combo, Critical.Pair, A.Gender, A.Ear, Type) %>%  
  
  group_map(.f = ~ write_csv(.x, file = paste0("C:Stimuli/Experiment_1/Lists/Filler.0", .y$Set.Combo, "_", .y$A.Gender, "_", .y$A.Ear, ".csv")
  ))
```

## Test Phase  
### Test Items  
```{r Test Phase}
# Table
tibble(
  
  Phase = c(
    rep("Test", 6)
  ),
  
  Item.Type = c(
    rep("Test", 6)
  ),  
  
  Talker.A = c(
    "ashi.25",
    "ashi.30",
    "ashi.40",
    "ashi.45",
    "ashi.50",
    "ashi.70"
  ),
  
  Talker.B = c(
    rep("NA", 6)
  ),
  
  Item.Number = 1:6
  
)%>%
  
  ## Attended Talker x First Talker
  crossing(
    Talker.A_Gender = c(
      "Female", 
      "Male"
    ),
    
    Block = 1:12
  ) %>%
  
  ### Group every 2 blocks
  mutate(
    First_Talker = case_when( 
      abs(Block %% 4) == 1 &
        Talker.A_Gender == "Male"
      ~ "Male",
      
      abs(Block %% 4) == 2 &
        Talker.A_Gender == "Male"
      ~ "Male",
      
      abs(Block %% 4) == 3 &
        Talker.A_Gender == "Female"
      ~ "Male",      
      
      abs(Block %% 4) == 0 &
        Talker.A_Gender == "Female"
      ~ "Male",  
      
      abs(Block %% 4) == 1 &
        Talker.A_Gender == "Female"
      ~ "Female",
      
      abs(Block %% 4) == 2 &
        Talker.A_Gender == "Female"
      ~ "Female",
      
      abs(Block %% 4) == 3 &
        Talker.A_Gender == "Male"
      ~ "Female",
      
      abs(Block %% 4) == 0 &
        Talker.A_Gender == "Male"
      ~ "Female"
    ),
    
    ### 2 possible Lists: starting with the Female talker or the Male talker
    Test_Version = case_when(
      First_Talker == "Female"
      ~ "A",
      T ~ "B"
    )
  ) %>%
  
  ### repetition of File within List
  mutate(
    reps = 1
  ) %>%
  
  # feedback
  mutate(
    feedback = FALSE
  ) %>%
  
  # File name
  mutate(
    filename = paste0(
      "Test",
      sep = "_",
      
      case_when(
        Talker.A_Gender == "Female"
        ~ paste0("F", sep = "."), 
        T ~ paste0("M", sep = ".")
      ),
      
      Item.Number,
      sep = "_",   
      Talker.A,
      paste0(".wav")
    )
  ) %>%
  
  view() %>%
  
  # CSV Files
  
  ## Remove file columns <- all but file names
  select(-c(First_Talker)) %>%
  
  ## Group files into list 
  group_by(Test_Version) %>%
  
  group_map(.f = ~ write_csv(.x, file = paste0("C:Stimuli/Experiment_1/Lists/Test.", .y$Test_Version, ".csv")
  ))
```

# Concatenate CSV files  
```{r Concate}

# Origin
setwd("Stimuli/Experiment_1/Lists/")

# Destination
folder <- paste0("Stimuli/Experiment_1/Lists/Total/")

# Individual Lists
## Critical Lists 
C1 <- fread("Critical.01.csv")
C2 <- fread("Critical.02.csv")
C3 <- fread("Critical.03.csv")
C4 <- fread("Critical.04.csv")
C5 <- fread("Critical.05.csv")
C6 <- fread("Critical.06.csv")
C7 <- fread("Critical.07.csv")
C8 <- fread("Critical.08.csv")

C9 <- fread("Critical.09.csv")
C10 <- fread("Critical.10.csv")
C11 <- fread("Critical.11.csv")
C12 <- fread("Critical.12.csv")
C13 <- fread("Critical.13.csv")
C14 <- fread("Critical.14.csv")
C15 <- fread("Critical.15.csv")
C16 <- fread("Critical.16.csv")

## Filler Lists
F1 <- fread("Filler.01_Female_Left.csv")
F2 <- fread("Filler.02_Male_Right.csv")
F3 <- fread("Filler.03_Female_Right.csv")
F4 <- fread("Filler.04_Male_Left.csv")

## Test Lists
TA <- fread("Test.A.csv")
TB <- fread("Test.B.csv")


# Total Lists
L01 <- rbind(C1, F1, TA, fill=TRUE) 
L02 <- rbind(C1, F1, TB, fill=TRUE)
L03 <- rbind(C2, F1, TA, fill=TRUE)
L04 <- rbind(C2, F1, TB, fill=TRUE)

L05 <- rbind(C11, F1, TA, fill=TRUE)
L06 <- rbind(C11, F1, TB, fill=TRUE)
L07 <- rbind(C12, F1, TA, fill=TRUE)
L08 <- rbind(C12, F1, TB, fill=TRUE)

L09 <- rbind(C3, F2, TA, fill=TRUE)
L10 <- rbind(C3, F2, TB, fill=TRUE)
L11 <- rbind(C4, F2, TA, fill=TRUE)
L12 <- rbind(C4, F2, TB, fill=TRUE)

L13 <- rbind(C9, F2, TA, fill=TRUE)
L14 <- rbind(C9, F2, TB, fill=TRUE)
L15 <- rbind(C10, F2, TA, fill=TRUE)
L16 <- rbind(C10, F2, TB, fill=TRUE)

L17 <- rbind(C5, F3, TA, fill=TRUE)
L18 <- rbind(C5, F3, TB, fill=TRUE)
L19 <- rbind(C6, F3, TA, fill=TRUE)
L20 <- rbind(C6, F3, TB, fill=TRUE)

L21 <- rbind(C15, F3, TA, fill=TRUE)
L22 <- rbind(C15, F3, TB, fill=TRUE)
L23 <- rbind(C16, F3, TA, fill=TRUE)
L24 <- rbind(C16, F3, TB, fill=TRUE)

L25 <- rbind(C7, F4, TA, fill=TRUE)
L26 <- rbind(C7, F4, TB, fill=TRUE)
L27 <- rbind(C8, F4, TA, fill=TRUE)
L28 <- rbind(C8, F4, TB, fill=TRUE)

L29 <- rbind(C13, F4, TA, fill=TRUE)
L30 <- rbind(C13, F4, TB, fill=TRUE)
L31 <- rbind(C14, F4, TA, fill=TRUE)
L32 <- rbind(C14, F4, TB, fill=TRUE)
### (There was probably a more efficient way to do this, possibly using the table I was trying to create)

# Write CSV Files

## C1
write.csv(L01, "Materials.B_Shift.S_Gender.F_Ear.L_Test.A.csv")
write.csv(L02, "Materials.B_Shift.S_Gender.F_Ear.L_Test.B.csv")
## C2
write.csv(L03, "Materials.A_Shift.Sh_Gender.F_Ear.L_Test.A.csv")
write.csv(L04, "Materials.A_Shift.Sh_Gender.F_Ear.L_Test.B.csv")
## C11
write.csv(L05, "Materials.B_Shift.Sh_Gender.F_Ear.L_Test.A.csv")
write.csv(L06, "Materials.B_Shift.Sh_Gender.F_Ear.L_Test.B.csv")
## C12
write.csv(L07, "Materials.A_Shift.S_Gender.F_Ear.L_Test.A.csv")
write.csv(L08, "Materials.A_Shift.S_Gender.F_Ear.L_Test.B.csv")
## C3
write.csv(L09, "Materials.B_Shift.S_Gender.M_Ear.R_Test.A.csv")
write.csv(L10, "Materials.B_Shift.S_Gender.M_Ear.R_Test.B.csv")
## C4
write.csv(L11, "Materials.A_Shift.Sh_Gender.M_Ear.R_Test.A.csv")
write.csv(L12, "Materials.A_Shift.Sh_Gender.M_Ear.R_Test.B.csv")
## C9
write.csv(L13, "Materials.B_Shift.Sh_Gender.M_Ear.R_Test.A.csv")
write.csv(L14, "Materials.B_Shift.Sh_Gender.M_Ear.R_Test.B.csv")
## C10
write.csv(L15, "Materials.A_Shift.S_Gender.M_Ear.R_Test.A.csv")
write.csv(L16, "Materials.A_Shift.S_Gender.M_Ear.R_Test.B.csv")
## C5
write.csv(L17, "Materials.B_Shift.S_Gender.F_Ear.R_Test.A.csv")
write.csv(L18, "Materials.B_Shift.S_Gender.F_Ear.R_Test.B.csv")
## C6
write.csv(L19, "Materials.A_Shift.Sh_Gender.F_Ear.R_Test.A.csv")
write.csv(L20, "Materials.A_Shift.Sh_Gender.F_Ear.R_Test.B.csv")
## C15
write.csv(L21, "Materials.B_Shift.Sh_Gender.F_Ear.R_Test.A.csv")
write.csv(L22, "Materials.B_Shift.Sh_Gender.F_Ear.R_Test.B.csv")
## C16
write.csv(L23, "Materials.A_Shift.S_Gender.F_Ear.R_Test.A.csv")
write.csv(L24, "Materials.A_Shift.S_Gender.F_Ear.R_Test.B.csv")
## C7
write.csv(L25, "Materials.B_Shift.S_Gender.M_Ear.L_Test.A.csv")
write.csv(L26, "Materials.B_Shift.S_Gender.M_Ear.L_Test.B.csv")
## C8
write.csv(L27, "Materials.A_Shift.Sh_Gender.M_Ear.L_Test.A.csv")
write.csv(L28, "Materials.A_Shift.Sh_Gender.M_Ear.L_Test.B.csv")
## C13
write.csv(L29, "Materials.B_Shift.Sh_Gender.M_Ear.L_Test.A.csv")
write.csv(L30, "Materials.B_Shift.Sh_Gender.M_Ear.L_Test.B.csv")
## C14
write.csv(L31, "Materials.A_Shift.S_Gender.M_Ear.L_Test.A.csv")
write.csv(L32, "Materials.A_Shift.S_Gender.M_Ear.L_Test.B.csv")

# For Loop
#for(L in L01:L32){
#  write.csv( L, "List_", 01:32, ".csv" )
#}
### Trying to write a for loop below to write the csv files but one problem at a time
```

```{r Concate Table}
# Here we are generating the CSV files for each list. There are a total of *32* lists (described in Exp.1_Master file under writeups)

## How Lists are combined
tibble(
  Critical = c(
    'C1',
    'C2',
    'C3',
    'C4',
    'C5',
    'C6',
    'C7',
    'C8'
  )
) %>%
  
  crossing(
    if (
      Critical == 'C1'| 
      Critical == 'C2'|
      Critical == 'C3'|
      Critical == 'C4'
    ){
      Filler = c(
        'F2',
        'F3')
      
    } else {
      
      Filler = c(
        'F1',
        'F4')
    },
    ### Below I was trying to cross F2 & F3 with C1:C4, and F1 & F4 with C5:C8. The Filler List assignment is dependent on the Gender x Ear assignment in the Critical Lists!
    
    Test = c(
      'TA',
      'TB'
    )
  ) %>%
  view()
```


_______

# File Renaming

## Critical Items
```{r Critical Rename_S.F.L}
## Left: Female S Unambiguous; Right: Male Sh Unambiguous

Files <- list.files(path = "Stimuli/Experiment_1/Items_Critical/F.S_M.Sh/Nonambiguous/")


for (f in Files) {
  print(f)  
  
  old.files <- paste0(
    "Stimuli/Experiment_1/Items_Critical/F.S_M.Sh/Nonambiguous/", 
    f) 
  
  f.Category = gsub("^200ms", "Critical", f)
  f.left_Shift = gsub("F.S", "S", f.Category)
  f.left_Gender.Ear = gsub("_M.", ".F.L_", f.left_Shift)
  f.right_Shift = gsub("Sh", "Sh", f.left_Gender.Ear)
  f.right_Gender.Ear = gsub(".wav", ".M.R.wav", f.right_Shift)
  
  new.files <- paste0("Stimuli/Experiment_1/Items_Critical/1/", f.right_Gender.Ear)
  
  file.rename(old.files, new.files)
}
```


```{r Critical Rename_As.F.L}
## Left: Female S Ambiguous; Right: Male Sh Ambiguous

Files <- list.files(path = "Stimuli/Experiment_1/Items_Critical/F.S_M.Sh/Ambiguous/")

for (f in Files) {
  
  
  old.files <- paste0(
    "Stimuli/Experiment_1/Items_Critical/F.S_M.Sh/Ambiguous/", 
    f) 
  
  f.Category = gsub("^200ms", "Critical", f)
  
  f.left_Shift = gsub("F.Xs", "As", f.Category)
  f.left_Gender.Ear = gsub("_M.", ".F.L_", f.left_Shift)
  f.right_Shift = gsub("Xsh", "Ash", f.left_Gender.Ear)
  f.right_Gender.Ear = gsub(".wav", ".M.R.wav", f.right_Shift)
  
  new.files <- paste0("Stimuli/Experiment_1/Items_Critical/2/", f.right_Gender.Ear)
  
  file.rename(old.files, new.files)
}
```

```{r Critical Rename_Sh.F.L}
## Left: Female Sh Unambiguous; Right: Male S Unambiguous
Files <- list.files(path = "Stimuli/Experiment_1/Items_Critical/F.Sh_M.S/Nonambiguous/")

for (f in Files) {
  
  old.files <- paste0(
    "Stimuli/Experiment_1/Items_Critical/F.Sh_M.S/Nonambiguous/", 
    f) 
  
  f.Category = gsub("^200ms", "Critical", f)
  f.left_Shift = gsub("F.Sh", "Sh", f.Category)
  f.left_Gender.Ear = gsub("_M.", ".F.L_", f.left_Shift)
  f.right_Shift = gsub("_s", "_S", f.left_Gender.Ear)
  f.right_Gender.Ear = gsub(".wav", ".M.R.wav", f.right_Shift)
  
  new.files <- paste0("Stimuli/Experiment_1/Items_Critical/3/", f.right_Gender.Ear)
  
  file.rename(old.files, new.files)
}
```

```{r Critical Rename_Ash.F.L}
## Left: Female Sh Ambiguous; Right: Male S Ambiguous
Files <- list.files(path = "Stimuli/Experiment_1/Items_Critical/F.Sh_M.S/Ambiguous/")

for (f in Files) {
  
  old.files <- paste0(
    "Stimuli/Experiment_1/Items_Critical/F.Sh_M.S/Ambiguous/", 
    f) 
  
  f.Category = gsub("^200ms", "Critical", f)
  f.left_Shift = gsub("F.Xsh", "Ash", f.Category)
  f.left_Gender.Ear = gsub("_M.", ".F.L_", f.left_Shift)
  f.right_Shift = gsub("Xs", "As", f.left_Gender.Ear)
  f.right_Gender.Ear = gsub(".wav", ".M.R.wav", f.right_Shift)
  
  new.files <- paste0("Stimuli/Experiment_1/Items_Critical/4/", f.right_Gender.Ear)
  
  file.rename(old.files, new.files)
}
```

```{r Critical Rename_S.M.L}
## Left: Male S Unambiguous; Right: Female Sh Unambiguous
Files <- list.files(path = "Stimuli/Experiment_1/Items_Critical/M.S_F.Sh/Nonambiguous/")

for (f in Files) {
  
  old.files <- paste0(
    "Stimuli/Experiment_1/Items_Critical/M.S_F.Sh/Nonambiguous/", 
    f) 
  
  f.Category = gsub("^200ms", "Critical", f)
  f.left_Shift = gsub("M.S.", "S.", f.Category)
  f.left_Gender.Ear = gsub("_F.", ".M.L_", f.left_Shift)
  f.right_Shift = gsub("L_Sh.", "L_Sh.", f.left_Gender.Ear)
  f.right_Gender.Ear = gsub(".wav", ".F.R.wav", f.right_Shift)
  
  new.files <- paste0("Stimuli/Experiment_1/Items_Critical/5/", f.right_Gender.Ear)
  
  file.rename(old.files, new.files)
}
```

```{r Critical Rename_As.M.L}
## Left: Male S Ambiguous; Right: Female Sh Ambiguous
Files <- list.files(path = "Stimuli/Experiment_1/Items_Critical/M.S_F.Sh/Ambiguous/")

for (f in Files) {
  
  old.files <- paste0(
    "Stimuli/Experiment_1/Items_Critical/M.S_F.Sh/Ambiguous/",
    f) 
  
  f.Category = gsub("^200ms", "Critical", f)
  f.left_Shift = gsub("M.Xs", "As", f.Category)
  f.left_Gender.Ear = gsub("_F.", ".M.L_", f.left_Shift)
  f.right_Shift = gsub("Xsh", "Ash", f.left_Gender.Ear)
  f.right_Gender.Ear = gsub(".wav", ".F.R.wav", f.right_Shift)
  
  new.files <- paste0("Stimuli/Experiment_1/Items_Critical/6/", f.right_Gender.Ear)
  
  file.rename(old.files, new.files)
}
```

```{r Critical Rename_Sh.M.L}
## Left: Male Sh Unambiguous; Right: Female S Unambiguous
Files <- list.files(path = "Stimuli/Experiment_1/Items_Critical/M.Sh_F.S/Nonambiguous/")

for (f in Files) {
  
  old.files <- paste0(
    "Stimuli/Experiment_1/Items_Critical/M.Sh_F.S/Nonambiguous/", 
    f) 
  
  f.Category = gsub("^200ms", "Critical", f)
  f.left_Shift = gsub("M.Sh", "Sh", f.Category)
  f.left_Gender.Ear = gsub("_F.", ".M.L_", f.left_Shift)
  f.right_Shift = gsub("S", "S", f.left_Gender.Ear)
  f.right_Gender.Ear = gsub(".wav", ".F.R.wav", f.right_Shift)
  
  new.files <- paste0("Stimuli/Experiment_1/Items_Critical/7/", f.right_Gender.Ear)
  
  file.rename(old.files, new.files)
}
```

```{r Critical Rename_Ash.M.L}
## Left: Male Sh Ambiguous; Right: Female S Ambiguous
Files <- list.files(path = "Stimuli/Experiment_1/Items_Critical/M.Sh_F.S/Ambiguous/")

for (f in Files) {
  
  old.files <- paste0(
    "Stimuli/Experiment_1/Items_Critical/M.Sh_F.S/Ambiguous/",
    f) 
  
  f.Category = gsub("^200ms", "Critical", f)
  f.left_Shift = gsub("M.Xsh", "Ash", f.Category)
  f.left_Gender.Ear = gsub("_F.", ".M.L_", f.left_Shift)
  f.right_Shift = gsub("Xs", "As", f.left_Gender.Ear)
  f.right_Gender.Ear = gsub(".wav", ".F.R.wav", f.right_Shift)
  
  new.files <- paste0("Stimuli/Experiment_1/Items_Critical/8/", f.right_Gender.Ear)
  
  file.rename(old.files, new.files)
}
```

_____

```{r Critical List/Materials}

Files <- list.files(path = "Stimuli/Experiment_1/Items_Critical/8B/")

for (f in Files) {
  
  old.files <- paste0(
    "Stimuli/Experiment_1/Items_Critical/8B/",
    f) 
  
  f.list = gsub("Critical", "Critical_08.X", f)
  f.materials = gsub(".X", ".B", f.list)
  
  new.files <- paste0("Stimuli/Experiment_1/Items_Critical/8/", f.materials)
  
  file.rename(old.files, new.files)
}
```
________

```{r Filler Rename}

Files <- list.files(path = "Stimuli/Experiment_1/Items_Filler/B/Version_2/")

for (f in Files) {
  
  old.files <- paste0(
    "Stimuli/Experiment_1/Items_Filler/B/Version_2/",
    f) 
  
  f.new = gsub("Filler_", "Filler_02_", f)
  
  new.files <- paste0("Stimuli/Experiment_1/Items_Filler/B/Version_2/", f.new)
  
  file.rename(old.files, new.files)
}
```
________