---
title: "Automaticity of Speech Prediction Figures"
author: "Rachel"
date: \today
geometry: margin = 2cm
header-includes:
  - \usepackage{booktabs}
  - \usepackage{siunitx}
  - \usepackage{tabto}
  - \usepackage{soul}
  - \usepackage{xcolor}
  - \usepackage{placeins}
  - \usepackage{lscape}
  - \usepackage{animate}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \makeatletter\renewcommand{\fps@table}{!ht}\makeatother
  - \setstcolor{red}
  - \usepackage{sectsty}
  - \sectionfont{\color{blue}} 
  - \subsectionfont{\color{blue}}
  - \subsubsectionfont{\color{darkgray}}

output:
  pdf_document: 
    fig_caption: yes
    fig_width: 7
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 4
  fontsize: 10pt
editor_options: 
  chunk_output_type: inline
---   
***
# Housekeeping   
The purpose of this file is to create prediction figures for the Summer 2022 Fellowship Poster (poster presentation 1).

*Color file here: http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf*   

## Knitting    
```{r Knitting, include=F}

library(knitr)

opts_chunk$set(
  dev = 'pdf',
  comment = "", 
  echo = FALSE, 
  warning = TRUE, 
  message = TRUE,
  cache = FALSE, 
  size = "small",
  tidy.opts = list(width.cutoff = 200),
  fig.width = 8, 
  fig.height = 4.5, 
  fig.align = "center")

def.chunk.hook  <- knitr::knit_hooks$get("chunk")

knitr::knit_hooks$set(
  chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
    ifelse(
      options$size != "normalsize", 
      paste0(
        "\n \\", 
        options$size,
        "\n\n", 
        x, 
        "\n\n \\normalsize"), 
        x)
})

color_block = function(color) {
    function(x, options)        sprintf('\\color{%s}\\begin{verbatim}%s\\end{verbatim}\\color{black}', color, x)
}
knitr::knit_hooks$set(error = color_block('red'))
knitr::knit_hooks$set(warning = color_block('orange'))
```

## Libraries   
```{r Library, include=F}
library(tidyverse)
library(magrittr)
library(broom)          # for extraction of coefficients
library(gganimate)      # to animate plots
library(RColorBrewer)   # to select brewer colors
library(kableExtra) 
library(lme4)
library(lmerTest)
library(ggpubr)
```

```{r, include=F}
options(width = 110)
theme_set(theme_bw())
```

```{r functions, include=FALSE}
source("C:/Users/Rachel/Documents/BCSC 206.207/BCSC_207/scripts/experiment-reports/functions-for-experiment-reports.R")
```

## Figure 1A: If attention **is** Required
```{r Figure 1A}

### From BCS 206 --> I think this is the dataframe?
#### Figure out how to change later!
d.vot <- tibble(VOT = seq(20, 80, 12))
d.vot %>%
    ggplot(aes(x = VOT)) +

### Expectations marker  
  geom_segment(
    x = 50, xend = 50,
    y = 0, yend = 1,
    color = "lightgray", 
    linetype = 2,
    size = 1,
    alpha = .25) +
  
### Talker A
  stat_function(
    fun = function(x) 
    plogis(x, 35, 1.2),
    color = "orange",
    size = 2) +
  annotate(
    geom = "text", 
    label = "Talker A \n ?Sh", 
    x = 40.5, 
    y = .75, 
    color = "orange") +
  geom_segment(
    x = 35, xend = 35,
    y = 0, yend = 1,
    color = "orange", 
    linetype = 2,
    size = 1,
    alpha = .3) +
    
### Talker B 
  stat_function(
    fun = function(x) 
    plogis(x, 50, .6),
    color = "lightskyblue", 
    size = 2) +
  annotate(
    geom = "text", 
    label = "Talker B \n ?S", 
    x = 55, 
    y = .75, 
    color = "lightskyblue3") +
  geom_segment(
    x = 65, xend = 65,
    y = 0, yend = 1,
    color = "lightskyblue", 
    linetype = 2,
    size = 1,
    alpha = .4) +
  
### Prior Expectations Estimate
  stat_function(
    fun = function(x) 
    plogis(x, 50, .6),
    color = "blacK",
    linetype = 2, 
    size = 2) +
  annotate(
    geom = "text", 
    label = "Prior \n Expectation \n Estimate", 
    x = 44.5, 
    y = .25, 
    color = "black") +

### Title & Axes
  scale_x_continuous('Percent "S" energy \n (not observed)') +
  scale_y_continuous('Proportion of "Sh" responses') +
  ggtitle("Figure 1A: If Adaptation Requires Attention")
```

## Figure 1B: If attention **is not** Required
```{r Figure 1B}

### From BCS 206 --> I think this is the dataframe?
#### Figure out how to change later!
d.vot <- tibble(VOT = seq(20, 80, 12))
d.vot %>%
ggplot(aes(x = VOT)) +
  
### Expectations marker  
  geom_segment(
    x = 50, xend = 50,
    y = 0, yend = 1,
    color = "lightgray", 
    linetype = 2,
    size = 1,
    alpha = .25) +
  
### Talker A
  stat_function(
    fun = function(x)
    plogis(x, 35, 1.2),
    color = "orange", 
    size = 2) +
  annotate(
    geom = "text", 
    label = "Talker A \n ?Sh", 
    x = 40.5, 
    y = .75, 
    color = "orange") +
  geom_segment(
    x = 35, xend = 35,
    y = 0, yend = 1,
    color = "orange", 
    linetype = 2,
    size = 1,
    alpha = .3) +
      
### Talker B 
  stat_function(
    fun = function(x) 
    plogis(x, 65, 1.2),
    color = "lightskyblue", 
    size = 2) +
  annotate(
    geom = "text", 
    label = "Talker B \n ?S", 
    x = 70.5, 
    y = .75, 
    color = "lightskyblue3") +
  geom_segment(
    x = 65, xend = 65,
    y = 0, yend = 1,
    color = "lightskyblue", 
    linetype = 2,
    size = 1,
    alpha = .4) +
  
### Prior Expectation Estimate
  stat_function(
    fun = function(x) 
    plogis(x, 50, .6),
    color = "blacK", 
    linetype = 2, 
    size = 2) +
  annotate(
    geom = "text", 
    label = "Prior \n Expectation \n Estimate", 
    x = 44.5, 
    y = .25, 
    color = "black") +

### Title & Axes
  scale_x_continuous('Percent "S"" energy \n (not observed)' ) +
  scale_y_continuous('Proportion of "Sh" responses') +
  ggtitle("Figure 1B: If Adaptation is Automatic") 
```

## Figure 1C: No Adaptation
```{r Figure 1C}

### From BCS 206 --> I think this is the dataframe?
#### Figure out how to change later!
d.vot <- tibble(VOT = seq(20, 80, 12))
d.vot %>%
    ggplot(aes(x = VOT)) +
  
### Expectations marker  
  geom_segment(
    x = 50, xend = 50,
    y = 0, yend = 1,
    color = "lightgray", 
    linetype = 2,
    size = 1,
    alpha = .25) +
  
### Talker A
  stat_function(
    fun = function(x) 
    plogis(x, 50, .6),
    color = "orange",
    size = 2,
    alpha = .9 )+
  annotate(
    geom = "text", 
    label = "Talker A \n ?Sh", 
    x = 47, 
    y = .75, 
    color = "orange") +
  geom_segment(
    x = 35, xend = 35,
    y = 0, yend = 1,
    color = "orange", 
    linetype = 2,
    size = 1,
    alpha = .3) +
    
### Talker B 
  stat_function(
    fun = function(x) 
    plogis(x, 50, .6),
    color = "lightskyblue", 
    size = 2,
    alpha = .6) +
  annotate(
    geom = "text", 
    label = "Talker B \n ?S", 
    x = 54, 
    y = .5, 
    color = "lightskyblue3") +
  geom_segment(
    x = 65, xend = 65,
    y = 0, yend = 1,
    color = "lightskyblue", 
    linetype = 2,
    size = 1,
    alpha = .4) +
  
  ### Prior Expectations Estimate
  stat_function(
    fun = function(x) 
    plogis(x, 50, .6),
    color = "blacK",
    linetype = 2, 
    size = 2) +
  annotate(
    geom = "text", 
    label = "Prior \n Expectation \n Estimate", 
    x = 44.5, 
    y = .25, 
    color = "black") +
  

### Title & Axes
  scale_x_continuous('Percent "S" energy \n (not observed)') +
  scale_y_continuous('Proportion of "Sh" responses') +
  ggtitle("Figure 1C: If No Adaptation Occurs")
```
