---
title: "Experiment 1 List Design"
author: "Rachel"
date: \today
geometry: margin = 2cm
header-includes:
  - \usepackage{booktabs}
  - \usepackage{siunitx}
  - \usepackage{tabto}
  - \usepackage{soul}
  - \usepackage{xcolor}
  - \usepackage{placeins}
  - \usepackage{lscape}
  - \usepackage{animate}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \makeatletter\renewcommand{\fps@table}{!ht}\makeatother
  - \setstcolor{red}
  - \usepackage{sectsty}
  - \sectionfont{\color{blue}} 
  - \subsectionfont{\color{blue}}
  - \subsubsectionfont{\color{darkgray}}

output:
  pdf_document: 
    fig_caption: yes
    fig_width: 7
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 4
  fontsize: 10pt
editor_options: 
  chunk_output_type: inline
---   
***
# Housekeeping   
The purpose of this file is to create the lists for Experiment 1
*Color file here: http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf*   

## Knitting    
```{r Knitting, include=F}

library(knitr)

opts_chunk$set(
  dev = 'pdf',
  comment = "", 
  echo = FALSE, 
  warning = TRUE, 
  message = TRUE,
  cache = FALSE, 
  size = "small",
  tidy.opts = list(width.cutoff = 200),
  fig.width = 8, 
  fig.height = 4.5, 
  fig.align = "center")

def.chunk.hook  <- knitr::knit_hooks$get("chunk")

knitr::knit_hooks$set(
  chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
    ifelse(
      options$size != "normalsize", 
      paste0(
        "\n \\", 
        options$size,
        "\n\n", 
        x, 
        "\n\n \\normalsize"), 
        x)
})

color_block = function(color) {
    function(x, options)        sprintf('\\color{%s}\\begin{verbatim}%s\\end{verbatim}\\color{black}', color, x)
}
knitr::knit_hooks$set(error = color_block('red'))
knitr::knit_hooks$set(warning = color_block('orange'))
```

## Libraries   
```{r Library, include=F}
library(tidyverse)
library(magrittr)
library(broom)          # for extraction of coefficients
library(gganimate)      # to animate plots
library(RColorBrewer)   # to select brewer colors
library(kableExtra) 
library(lme4)
library(lmerTest)
library(ggpubr)
```

```{r, include=F}
options(width = 110)
theme_set(theme_bw())
```

# Code 9.21   
## Critical Pairs   
```{r List.Design_Ciritcal.Pairs}
# Table with the information on how the stims should be paired + Accent x Gender x Ear assignment

tibble(
  Attended.Category = c(
  ## Materials A
    rep("sh", 10),
    rep("s", 10),

  ## Materials B
    rep("s", 10),
    rep("sh", 10)
  ),
  
  Attended.Word = c(
  ## Materials A
    "Ambition",
    "Machinery",
    "Brochure",
    "Official",
    "Crucial",
    "Pediatrician",
    "Flourishing",
    "Reassure",
    "Graduation",
    "Vacation",
    "Parasite",
    "Obscene",
    "Medicine",
    "Tennessee",
    "Penninsula",
    "Hallucinate",
    "Arkansas",
    "Compensate",
    "Dinosaur",
    "Rehearsal",
    
  ## Materials B
    "Pregnancy",
    "Democracy",
    "Embassy",
    "Legacy",
    "Reconcile",
    "Personal",
    "Eraser",
    "Episode",
    "Literacy",
    "Coliseum",
    "Initial",
    "Beneficial",
    "Negotiate",
    "Commercial",
    "Parachute",
    "Efficient",
    "Publisher",
    "Glacier",
    "Refreshing",
    "Impatient"  
  ),
  
  Unattended.Category = c(
  ## Materials B
    rep("s", 10),
    rep("sh", 10),
 
  ## Materials A
    rep("sh", 10),
    rep("s", 10)
  ),
    
  Unattended.Word = c(
  ## Materials B
    "Pregnancy",
    "Democracy",
    "Embassy",
    "Legacy",
    "Reconcile",
    "Personal",
    "Eraser",
    "Episode",
    "Literacy",
    "Coliseum",
    "Initial",
    "Beneficial",
    "Negotiate",
    "Commercial",
    "Parachute",
    "Efficient",
    "Publisher",
    "Glacier",
    "Refreshing",
    "Impatient",
    
  ## Materials A
    "Ambition",
    "Machinery",
    "Brochure",
    "Official",
    "Crucial",
    "Pediatrician",
    "Flourishing",
    "Reassure",
    "Graduation",
    "Vacation",
    "Parasite",
    "Obscene",
    "Medicine",
    "Tennessee",
    "Penninsula",
    "Hallucinate",
    "Arkansas",
    "Compensate",
    "Dinosaur",
    "Rehearsal"
  )) %>% 
  
# Possible Assignments (Accent x Gender x Ear)
crossing(
  Assignment_Talker.To.Accent = c(
    "Attended: sh-Biased", 
    "Attended: s-Biased"
  )
) %>%
  
mutate(
  Assignment_Talker.To.Shift =   
    case_when(
      Assignment_Talker.To.Accent == "Attended: sh-Biased" 
        & Attended.Category == "sh" ~ "Attended: Shifted (S)",
      Assignment_Talker.To.Accent == "Attended: s-Biased" 
       & Attended.Category == "s" ~ "Attended: Shifted (S)",
      T ~ "Attended: Unshifted (U)"
  )
) %>%
  
crossing(
  Assignment_Talker.To.Gender = c(
    "Attended: Female (F)", 
    "Attended: Male (M)"
  ),
  
  Assignment_Talker.To.Ear = c(
    "Attended: Left (L)", 
    "Attended: Right (R)"
  )
) %>%


# Changing file names --> Based on the *Attended Talker*
mutate(
  filename = paste0(
   
  ## s/sh Bias      
    case_when(
      Assignment_Talker.To.Accent == 
        "Attended: sh-Biased" & Attended.Category == "sh" ~ 
        paste0("S", sep = ".",  substr(Attended.Word, 1, 5)),
      Assignment_Talker.To.Accent == 
        "Attended: s-Biased" & Attended.Category == "s" ~ 
        paste0("S", sep = ".",  substr(Attended.Word, 1, 5)),
      T ~ paste0("U", sep = ".",  substr(Attended.Word, 1, 5))
    ),
    
    ### substr(Attended.Word, 1, 5) --> truncates the file name to include the first 5 characters of the word assigned to the attended talker --> need at least 5 characters to differentiate parachute from parasite
    
  ## M/F Gender
    case_when(
      Assignment_Talker.To.Gender == 
        "Attended: Female (F)" ~ paste0(sep = ".", "F"), 
      T ~ paste0(sep = ".", "M")
    ),
    
  ## L/R Ear
    case_when(
      Assignment_Talker.To.Ear == 
        "Attended: Left (L)" ~ paste0(sep = ".", "L"), 
      T ~ paste0(sep = ".", "R")
    )
)) %>% 
 
### to assign the files to the appropriate lists, I was thinking of using the row numbers in some way? I might just have to do it manually though because I'm not sure if it works well systematically?
  
view()
```

## Key for File Names

Symbol | Meaning
------------------------------
 S.    | Shifted (ambiguous)
 U.    | Unshifted (unambiguous)
.M     | Male gender assignment
.F     | Female gender assignment
.L     | Left ear
.R     | Right ear    


## Filler Pairs   
```{r List.Design_Filler.Pairs}
tibble(
  Set = c(
    rep("A", 20),
    rep("B", 20),
    rep("C", 20)
  ), 

  Filler.Word = c(
  # Set A
    "ameri",
    "blueb",
    "camer",
    "direc",
    "dynam",
    "garde",
    "hambu",
    "hurdl",
    "inhab",
    "keybo",
    "lengt",
    "linge",
    "melan",
    "napki",
    "ornam",
    "pinea",
    "purga",
    "thera",
    "tutor",
    "wealt",
    
  # Set B
    "baker",
    "bully",
    "conti",
    "docum",
    "eight",
    "gramm",
    "ident",
    "inter",
    "knowi",
    "letha",
    "lobby",
    "membe",
    "negat",
    "outnu",
    "parak",
    "plato",
    "tacti",
    "titan",
    "umbre",
    "world",
    
  # Set C
    "balle",
    "burgl",
    "domin",
    "embod",
    "gulli",
    "honey",
    "illum",
    "ironi",
    "lamin",
    "liabi",
    "marin",
    "metir",
    "night",
    "panic",
    "pilgr",
    "predi",
    "termi",
    "turbu",
    "under",
    "wink"
  ),
  
  Non.Word = c(
  # Set A
    "womin",
    "ungel",
    "tileg",
    "rimke",
    "rakil",
    "perku",
    "nomer",
    "namue",
    "logel",
    "lened",
    "kelab",
    "inpak",
    "hinta",
    "gondi",
    "gaire",
    "bikan",
    "balib",
    "amala",
    "ailou",
    "acomi",
      
  # Set B
    "woyal",
    "touna",
    "rylig",
    "rawam",
    "ploup",
    "omper",
    "nempr",
    "mibge",
    "meidn",
    "kermi",
    "itemp",
    "aknid",
    "ibira",
    "halke",
    "ganla",
    "dadig",
    "bamte",
    "aneme",
    "lilgr",
    "admun",
  
  # Set C
   "youmg",
   "tymol",
   "tamic",
   "rengi",
   "pouri",
   "oumik",
   "nirit",
   "mikid",
   "kalde",
   "imdai",
   "kloum",
   "halom",
   "gerbu",
   "galli",
   "emhou",
   "dilku",
   "bawes",
   "anoli",
   "alnad",
   "aigi"
  )
) %>%
  
crossing(
  Assignment_Talker.To.Gender = c(
    "Attended: Female (F)", 
    "Attended: Male (M)"
  ),
  
  Assignment_Talker.To.Ear = c(
    "Attended: Left (L)", 
    "Attended: Right (R)"
  )
) %>%
  
  
# Changing file names --> Name based on the FillerWord
mutate(
  filename = paste0(
   
  ## M/F Gender
    case_when(
      Assignment_Talker.To.Gender == 
        "Attended: Female (F)" ~ paste0("N", sep = ".", Filler.Word, sep = ".", "F"), 
      T ~ paste0("N", sep = ".", Filler.Word, sep = ".", "M")
    ),
    
  ## L/R Ear
    case_when(
      Assignment_Talker.To.Ear == 
        "Attended: Left (L)" ~ paste0(sep = ".", "L"), 
      T ~ paste0(sep = ".", "R")
    )
)) %>% 
  
mutate (
   case_when(
      List == 
      row.number/4 == interger
   )
 ) %>%
  
View()
```


### Help  
```{r help}
?crossing
?mutate

### I need to create a column in the table that notes which lists assignment the audio files should be included in, which can then be filtered down by list.
```
